name: 'Cache'
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      force:        
        type: choice
        description: Update phars by force
        options:
        - true
        - false
        default: 'false'
        required: false
  schedule:
    - cron: '0 * * * *'
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      run: bash scripts/cache.sh
      env:
        FORCE: ${{ github.event.inputs.force }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
